debug_preprocess: preprocessing.cpp
	g++ -g -std=c++11 -o preprocessing preprocessing.cpp

preprocess: preprocessing.cpp
	g++ -std=c++11 -o preprocessing preprocessing.cpp

namegenerator: namegenerator.cpp
	g++ -std=c++11 -o namegenerator namegenerator.cpp

debug_namegenerator: namegenerator.cpp
	g++ -g -std=c++11 -o namegenerator namegenerator.cpp
